### ISSUE TITLE
CHANNEL sendToAllMembers 함수 기능 수정

### ISSUE THREAD

**Issue by Rillmo** [Commit-The-Frog/IRC#55]
현재는 자기 자신에게는 메세지가 전송되지 않음.
PRIVMSG는 자기 자신에게 보내지 않고,
KICK의 경우 자기 자신에게도 메세지를 보내야 하므로 수정이 필요

**Comment by minjacho42** [comment]
sender nick에 빈문자열 넣으면 전체에 전송 가능합니다
